//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionesPago
    {
        public short codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> dias { get; set; }
        public Nullable<bool> anticipo { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
    }
}
