//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoProveedores
    {
        public int idContactos { get; set; }
        public Nullable<int> idproveedor { get; set; }
        public string nombre { get; set; }
        public string correo1 { get; set; }
        public string correo2 { get; set; }
        public string telefono { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
