//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesProveedor
    {
        public int idDetalles { get; set; }
        public Nullable<int> proveedor { get; set; }
        public string perfil { get; set; }
        public string cotizaciones { get; set; }
        public string pedidos { get; set; }
        public string facturas { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
