//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRequisicion2
    {
        public int idDetalleReq { get; set; }
        public Nullable<bool> trabajoSindicato { get; set; }
        public Nullable<bool> retencionImpuesto { get; set; }
        public Nullable<bool> altura { get; set; }
        public Nullable<bool> espaciosConfinados { get; set; }
        public Nullable<bool> electrico { get; set; }
        public Nullable<bool> corte { get; set; }
        public Nullable<bool> soldadura { get; set; }
        public Nullable<bool> operacionMontacargas { get; set; }
        public Nullable<bool> izajesCarga { get; set; }
        public int preRequisicion { get; set; }
        public short departamento { get; set; }
        public int ejercicio { get; set; }
    
        public virtual Solicitud_Requisiciones Solicitud_Requisiciones { get; set; }
    }
}
