//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitacionReq
    {
        public int idInvitacion { get; set; }
        public Nullable<int> idProveedores { get; set; }
        public string status { get; set; }
        public string requisicion { get; set; }
        public Nullable<int> preRequisicion { get; set; }
        public Nullable<short> departamento { get; set; }
        public Nullable<int> ejercicio { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
