//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.ContactoProveedores = new HashSet<ContactoProveedores>();
            this.DetallesProveedor = new HashSet<DetallesProveedor>();
        }
    
        public int consecutivos { get; set; }
        public Nullable<int> proveedor { get; set; }
        public string razSoc { get; set; }
        public Nullable<decimal> padronProv { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string colonia { get; set; }
        public string ciudad { get; set; }
        public Nullable<int> codigoPostal { get; set; }
        public string fax { get; set; }
        public Nullable<short> tipo { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> actaCons { get; set; }
        public string representante { get; set; }
        public Nullable<int> cuenta { get; set; }
        public Nullable<int> centCost { get; set; }
        public Nullable<int> subCuenta { get; set; }
        public Nullable<int> subsubCuenta { get; set; }
        public string catOrg { get; set; }
        public Nullable<short> tipoProveedor { get; set; }
        public string razSoc2 { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactoProveedores> ContactoProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesProveedor> DetallesProveedor { get; set; }
    }
}
