//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCompras.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Requisiciones
    {
        public int preRequisicion { get; set; }
        public Nullable<int> preRequisicionAnt { get; set; }
        public string requisicion { get; set; }
        public Nullable<System.DateTime> fechaRequisicion { get; set; }
        public string uso { get; set; }
        public Nullable<System.DateTime> fechaNecesitar { get; set; }
        public short departamento { get; set; }
        public string ciclo { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> fechaRecepcion { get; set; }
        public int ejercicio { get; set; }
        public Nullable<int> solicitante { get; set; }
        public string observaciones { get; set; }
        public string liberaLocal { get; set; }
        public string liberaSeguridad { get; set; }
        public string liberaCapitalHumano { get; set; }
        public string liberaElectrico { get; set; }
        public string liberaAlmacen { get; set; }
        public string anexo { get; set; }
        public Nullable<short> departamentoSolicitante { get; set; }
        public string estatus { get; set; }
        public string partidaPresupuestal { get; set; }
    }
}
